// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationMvc.EfCore;

namespace WebApplicationMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContex))]
    [Migration("20210514213555_adedfields")]
    partial class adedfields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplicationMvc.Models.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Archivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cadena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Entero")
                        .HasColumnType("int");

                    b.Property<int>("Enum")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<float>("Flotante")
                        .HasColumnType("real");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaestroId")
                        .HasColumnType("int");

                    b.Property<long?>("MaestroId1")
                        .HasColumnType("bigint");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("booleano")
                        .HasColumnType("bit");

                    b.Property<decimal>("decimanl")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaestroId1");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("WebApplicationMvc.Models.Maestro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Booleano")
                        .HasColumnType("bit");

                    b.Property<string>("Cadena")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CualquierNombreDeCadena");

                    b.Property<decimal?>("Decimal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Entero")
                        .HasColumnType("int")
                        .HasColumnName("NombreEntero");

                    b.Property<int?>("Enum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Flotante")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Hora")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("WebApplicationMvc.Models.Detalle", b =>
                {
                    b.HasOne("WebApplicationMvc.Models.Maestro", "Maestro")
                        .WithMany("Detalles")
                        .HasForeignKey("MaestroId1");

                    b.Navigation("Maestro");
                });

            modelBuilder.Entity("WebApplicationMvc.Models.Maestro", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
